services:
  postgres:
    image: postgres:16
    container_name: crediya-postgres
    restart: unless-stopped
    env_file: .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init/crediya.sql:/docker-entrypoint-initdb.d/001_crediya.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  solicitudes:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crediya-solicitudes
    restart: unless-stopped
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      SPRING_R2DBC_URL: r2dbc:postgresql://${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      SPRING_R2DBC_USERNAME: ${POSTGRES_USER}
      SPRING_R2DBC_PASSWORD: ${POSTGRES_PASSWORD}

      # Usa UNA sola variable con flags válidas para HotSpot
      JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=70"

      # Asegura que no queden flags heredadas incompatibles
      _JAVA_OPTIONS: ""
      JDK_JAVA_OPTIONS: ""
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
