# src/main/resources/application-docker.yml
server:
  port: 8082
  address: 0.0.0.0

spring:
  application:
    name: "CrediYaMsSolicitudes"
  devtools:
    add-properties: false

  r2dbc:
    url: r2dbc:postgresql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}
    username: ${adapters.r2dbc.username}
    password: ${adapters.r2dbc.password}
    properties:
      schema: ${adapters.r2dbc.schema}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

cors:
  allowed-origins: "http://localhost:4200,http://127.0.0.1:4200,http://host.docker.internal:4200"

adapters:
  r2dbc:
    host: ${POSTGRES_HOST:postgres}
    port: ${POSTGRES_PORT:5432}
    database: ${POSTGRES_DB:crediya}
    schema: ${POSTGRES_SCHEMA:core}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin123}

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

app:
  jwt:
    secret: "d1UqRjMSI9She0oFsvhG/PIV1A/NN1Ke9RTohM/vVfE55Kle3Defav4aNLH01O7ocomXcnwXAAKqur8bg7CHdA=="
    issuer: "crediya-auth"

services:
  auth:
    url: http://crediya-autenticaciones:8082/api/v1/usuarios/
