server:
  port: 8082
spring:
  application:
    name: "CrediYaMsSolictudes"
  devtools:
    add-properties: false
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: crediya
    schema: auth
    username: admin
    password: admin123
logging:
  level:
    org.springframework.data.r2dbc: INFO
    org.springframework.r2dbc.core: INFO
    io.r2dbc.postgresql.QUERY: INFO
    io.r2dbc.postgresql.PARAM: INFO
    io.r2dbc.pool: WARN
    co.com.crediya: INFO
    root: INFO
app:
  jwt:
    secret: "d1UqRjMSI9She0oFsvhG/PIV1A/NN1Ke9RTohM/vVfE55Kle3Defav4aNLH01O7ocomXcnwXAAKqur8bg7CHdA=="
    issuer: "crediya-auth"
services:
  auth:
    url: http://localhost:8081/api/v1/usuarios/
